version: "3.8"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./client/:/usr/src/app
    stdin_open: true
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    restart: always
    depends_on:
      - db
    volumes:
      - ./server/:/usr/src/app
  db:
    image: postgres:14.1
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: art
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6-alpine
    restart: always
    ports:
      - 6379:6379
