export const fakeData = {
  objectID: "745166",
  artistDisplayName: "Lamqua",
  medium: "Watercolor and gouache",
  objectName: "Drawings Ornament & Architecture",
  title: "Design for a Hall Lamp",
  culture: "Greek, Attic",
  period: "Archaic",
  department: "Greek and Roman Art",
  objectDate: "last quarter of the 6th century B.C.",
  geographyType: "",
  artistNationality: "Chinese",
  city: "",
  state: "",
  county: "",
  country: "",
  region: "",
  subregion: "",
  locale: "",
  locus: "",
  excavation: "",
  objectWikidata_URL: "",
  primaryImage:
    "https://images.metmuseum.org/CRDImages/gr/original/DVB11430_1_ff.jpg",
  primaryImageSmall:
    "https://images.metmuseum.org/CRDImages/gr/web-large/DVB11430_1_ff.jpg",
  artistWikidata_URL: "https://www.wikidata.org/wiki/Q3359237",
  artistULAN_URL: "http://vocab.getty.edu/page/ulan/500028182",
  additionalImages: [
    "https://images.metmuseum.org/CRDImages/gr/original/DVB11430_2_ff.jpg",
  ],
};
